### ISSUE TITLE
Text is invisible in ESLint & Gulp

### ISSUE THREAD

**Issue by umayr** [ghuntley/terminator-solarized#9]
While running either eslint or gulp some part of the text is invisible, like this:

![screenshot from 2015-11-17 11 14 43](https://cloud.githubusercontent.com/assets/3071948/11204630/c21ae01e-8cce-11e5-94ed-ac06dd284478.png)

And it gets fixed when I replace `#002b36` to `#586e75`. As can be seen here:

![screenshot from 2015-11-17 11 15 40](https://cloud.githubusercontent.com/assets/3071948/11204629/c218867a-8cce-11e5-8717-0b069984b141.png)

I have this [fork](https://github.com/ghuntley/terminator-solarized/compare/master...umayr:master) with updated values, if it doesn't mess up anything else, I'd be happy to create a pull request.

**Comment by r-tanner-f** [comment]
+1

**Comment by NathanTurner** [comment]
~~I also have the issue, but this fix messes up the vim solarized colors plugin for me.~~

_Edit:_ This no longer reproduces for me.

**Comment by umayr** [comment]
@NathanTurner can you provide a screenshot?

**Comment by NathanTurner** [comment]
@umayr I am not sure what I hit earlier, but the problem I saw is not reproducing for me. I can toggle back and forth between a terminator profile without your change and a terminator profile with your change with no impact to my vim colors. I swore I had tried that earlier and vim had gone from that sweet dark blue background to a light-grey background. Please disregard the previous comment and accept an emphatic +1 instead :D

**Comment by ghuntley** [comment]
You all seem reasonably engaged. Do you want push privileges to take over
as a co-maintainer?

**Comment by umayr** [comment]
@NathanTurner No worries. Glad that worked out for you. It was really annoying bug, tbh.

As @r-tanner-f created a PR (#10) from my fork and that has been merged [79967a3f01edaedab3ec8016ecb1ecda458445d6], I'm closing this issue.

@ghuntley Sure. I'd be happy to contribute in any possible way.

**Comment by ghuntley** [comment]
Handing over day-to-day responsibilities to @umayr as I don't spend enough time on a Linux desktop these days. You now have contributor access to this repo.
